### Numpy

NumPy, Python programlama dili için büyük, çok boyutlu dizileri ve matrisleri destekleyen, bu diziler üzerinde çalışacak üst düzey matematiksel işlevler ekleyen bir kitaplıktır.

#### Numpy Array

Numpy Arraylar Python Listlerine benzer.
* Farkı numpy arraylar tek tip veri tutarlar.

In [3]:
import numpy as np

In [3]:
newNArray = np.array([1,2,3,5])

In [4]:
newNArray

array([1, 2, 3, 5])

In [5]:
type(newNArray)

numpy.ndarray

In [6]:
npArray = np.array(["a","b","c"])

In [7]:
npArray

array(['a', 'b', 'c'], dtype='<U1')

In [8]:
type(npArray)

numpy.ndarray

Eğer farklı veri tipleri olan değerler ile olusturmak istersek ; 

* String varsa hepsini en genel tip olan string tipine döndürür.

In [9]:
x = np.array([1,2,3,"a","b"])

In [10]:
x

array(['1', '2', '3', 'a', 'b'], dtype='<U11')

* Integer Float bulunuyorsa Float tipine döndürür.

In [11]:
y = np.array([1,2,3,4.2,5.1])

In [12]:
y

array([1. , 2. , 3. , 4.2, 5.1])

* Float-Integer-String üçlemesi varsa hepsi String olur.

In [13]:
z = np.array([1,2,3,4.2,5.1,"a","b"])

In [14]:
z

array(['1', '2', '3', '4.2', '5.1', 'a', 'b'], dtype='<U32')

### Numpy Array İstediğimiz Veri Tipini Verme

In [16]:
x = np.array([1,2,3,4.5,8.2], dtype="int32")

In [17]:
x

array([1, 2, 3, 4, 8])

In [18]:
y = np.array([1,2,3,4.5,8.2], dtype="str")

In [19]:
y

array(['1', '2', '3', '4.5', '8.2'], dtype='<U3')

* String karakterleri integer'a dönüştürülemez.

In [20]:
z = np.array([1,2,3,4.5,"a"], dtype="int32")

ValueError: invalid literal for int() with base 10: 'a'

* String sayısal veriler integer!a dönüştürülebilir.

In [21]:
z = np.array([1,2,3,4.5,"5"], dtype="int32")

In [22]:
z

array([1, 2, 3, 4, 5])

In [24]:
x = np.array(["4.2"] ,dtype="int32")

ValueError: invalid literal for int() with base 10: '4.2'

## Elemanları 0'dan Oluşan Arraylar (Zero Arrays)

In [26]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
np.zeros(10, dtype="str")

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

## Elemanları 0'dan Oluşan Multidimensional Arraylar (Zero Arrays)

In [29]:
np.zeros((3,4)) # 3 rows 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.zeros([3,8,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## Belirli Elemandan Oluşan Multidimensional Arraylar (Zero Arrays)

### np.full() fonksiyonu kullanılır.

In [31]:
np.full((4,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [32]:
np.full(4,5)

array([5, 5, 5, 5])

In [33]:
np.full((4,3),"a")

array([['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a'],
       ['a', 'a', 'a']], dtype='<U1')

## Ardışık Sayılardan Oluşan Multidimensional Arraylar (Zero Arrays)

In [36]:
np.arange(0,12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
np.arange(2,12)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

* Ardışıklık katsayısı da verilebilir.

In [38]:
np.arange(2,12,2)

array([ 2,  4,  6,  8, 10])

In [39]:
np.arange(12,2,-2)

array([12, 10,  8,  6,  4])

## Aralığı Eşit Uzaklıktaki Noktalara Bölmek

In [41]:
# Default olarak 50 noktaya böler.
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [42]:
# İstenilen nokta sayısına bölmek.
np.linspace(1,2,num =3)

array([1. , 1.5, 2. ])

In [45]:
# Son noktayı dahil etmemek
np.linspace(1,2,num =3, endpoint=False)

array([1.        , 1.33333333, 1.66666667])

## Random Integer'lardan Oluşan Array Oluşturmak

In [46]:
np.random.randint(1,10,(3,4))

array([[6, 8, 9, 1],
       [7, 8, 1, 4],
       [9, 8, 9, 4]])

In [47]:
np.random.randint(1,10,(3,5,5))

array([[[6, 7, 1, 2, 8],
        [6, 2, 2, 6, 8],
        [1, 4, 1, 1, 8],
        [5, 1, 8, 3, 7],
        [4, 6, 2, 8, 4]],

       [[8, 8, 2, 4, 4],
        [5, 6, 9, 3, 5],
        [9, 2, 1, 4, 3],
        [8, 1, 4, 7, 4],
        [2, 7, 1, 5, 5]],

       [[4, 4, 4, 9, 5],
        [3, 8, 2, 1, 5],
        [3, 3, 4, 7, 8],
        [4, 6, 1, 4, 3],
        [8, 3, 6, 7, 6]]])

In [48]:
np.random.randint(1,2)

1

## Identity Matrix

In [49]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## Array Operations

* Integer sayı ile çarpmak concatenation denilen tekrarlama yapar.

In [1]:
[4,2,3] * 3

[4, 2, 3, 4, 2, 3, 4, 2, 3]

* Numpy Arraylarda işlemler :
* Çarpma işlemi element-wise (eleman bazlı) olarak yapılır.

In [5]:
x = np.array([1,2,3])
y = np.array([4,5,6])

x * y

array([ 4, 10, 18])

In [6]:
x = np.array([1,2,3])
y = np.array([4,5,6,8])

x * y

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

* Toplama işlemi

In [7]:
a = [1,2,3]
b = [2,4,6]

a + b

[1, 2, 3, 2, 4, 6]

In [8]:
x = np.array([1,2,3])
y = np.array([4,5,6])

x + y

array([5, 7, 9])

## Array Attribute

In [10]:
x = np.zeros((3,4))

In [11]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
y = np.zeros((2,5,3))

In [13]:
y

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

* Array Dimension Öğrenme ---shape---

In [15]:
x.shape

(3, 4)

In [16]:
y.shape

(2, 5, 3)

* Kaç dimension olduğunu öğrenme ---ndim---

In [17]:
x.ndim

2

In [18]:
y.ndim

3

* Array eleman sayısı ---size---


In [19]:
x.size

12

In [20]:
y.size

30

* Array Veri Tipini Öğrenme ---dtype---

In [21]:
x.dtype

dtype('float64')

In [22]:
y.dtype

dtype('float64')

## Reshaping

* Son durumda iki array'in de aynı eleman sayısı olması (size aynı olacak)

In [27]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
a.ndim

1

In [29]:
a.size

10

In [30]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [31]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [32]:
a.reshape(2,5).ndim

2

* Eleman sayısı tutmazsa hata alınır!!

In [33]:
a.reshape(6,2)

ValueError: cannot reshape array of size 10 into shape (6,2)

### -1 ile Boyuta Karar Vermek

In [34]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## Concatenation

In [35]:
a = np.array([1,2,3,4])

In [40]:
b = np.array([3,4,5,6])

In [41]:
a

array([1, 2, 3, 4])

In [42]:
b

array([3, 4, 5, 6])

In [43]:
np.concatenate([a,b])

array([1, 2, 3, 4, 3, 4, 5, 6])

## Stack

* Stack yeni dimension ekleyip o dimension üzerinde concatenation yapmamızı sağlar

In [44]:
a = np.array([1,2,3,4])

In [45]:
b = np.array([5,6,7,8])

In [46]:
a

array([1, 2, 3, 4])

In [47]:
b

array([5, 6, 7, 8])

In [49]:
a.shape

(4,)

In [50]:
b.shape

(4,)

In [51]:
np.stack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
np.stack([a,b], axis=1)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

## Splitting

In [1]:
list = [10,20,30,40,50,60,70,80]

In [2]:
list

[10, 20, 30, 40, 50, 60, 70, 80]

In [4]:
np.split(list,[2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [5]:
np.split(list,[3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

### Split'in Sonucunu Birden Çok Değişkene Eşitleme

In [6]:
a, b = (1,10)

In [7]:
print(a)
print(b)

1
10


In [8]:
x, y, z = np.split(list,[2,6])

In [9]:
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80]


### VSPLIT

In [10]:
a = np.arange(20).reshape(2,10)

In [11]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [12]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [13]:
np.vsplit(a,[1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
np.vsplit(a,[1])[1]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

### HSPLIT

In [15]:
a = np.arange(20).reshape(2,10)

In [16]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [17]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [18]:
np.hsplit(a,[2])[0]

array([[ 0,  1],
       [10, 11]])

In [19]:
np.hsplit(a,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [21]:
a=np.arange(20).reshape(5,4) 

In [22]:
np.vsplit(a,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

## Sorting

In [25]:
a = np.array([20,12,65,85,5])

* Güncellemeden sıralama yapmak için ;

In [26]:
np.sort(a)

array([ 5, 12, 20, 65, 85])

In [27]:
a

array([20, 12, 65, 85,  5])

* Array güncellemesi için ;

In [28]:
a.sort()

In [29]:
a

array([ 5, 12, 20, 65, 85])

### ARGSORT

* Sıralama yaptıktan sonra sıralanmış halin indexlerini döndürür.

In [30]:
a = np.array([1,5,4,3,8,9])

In [31]:
idxs = np.argsort(a)

In [32]:
idxs

array([0, 3, 2, 1, 4, 5], dtype=int64)

## Multidimensional Array'lerde Indexleme

In [34]:
a = np.arange(1,21).reshape(4,5)

In [35]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
a[0]

array([1, 2, 3, 4, 5])

In [37]:
a[1]

array([ 6,  7,  8,  9, 10])

### Elemana Ulaşmak

In [38]:
a[0][0]

1

In [39]:
a[0,0]

1

In [40]:
a[1,1]

7

In [41]:
a[1][1]

7

* Array veri tipi neyse güncelleme yaparken ona cast olur

In [42]:
a [1,1] = 10

In [43]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [44]:
a[1,1] = 20.40

In [45]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Slice Indexing

In [46]:
a = np.arange(1,21).reshape(4,5)

In [47]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [48]:
a[1]

array([ 6,  7,  8,  9, 10])

In [49]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [50]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

## Fancy Indexing

In [52]:
a = np.array([1,2,3,4,5,6,7,8])

In [53]:
idxs = [1,3,5]
a[idxs]

array([2, 4, 6])